### ISSUE TITLE
.csv export followed by .csv import does not preserve original Pos. 

### ISSUE THREAD

**Issue by danieldietsch** [ultimate-pa/hanfor#178]
If I export a .csv and import the exported .csv again, I have a different order of items (based on Pos. column) in Hanfor

**Comment by samurous** [comment]
The underlying cause here is, that it is also possible to generate an CSV export from a subset (based on the filtered table) of requirements. The Pos. ist reffering to the position in the csv used to initialize the session.

I suggest we: Preserve the relative order in the generated CSV export. This would then preserve the exact Pos. when a full export is done.
