### ISSUE TITLE
hanfor formalization rules

### ISSUE THREAD

**Issue by IridescentL** [ultimate-pa/hanfor#183]
How to express formalization like "if S4 holds for less than 0.3s, 1lBeam.on holds for 1s" in hanfor? Seems like current provided rules is unable to express it.
![image](https://user-images.githubusercontent.com/24289271/92427899-444af780-f1c0-11ea-8cec-c47138250b1e.png)
I see that we can modify patterns in config.py file, so can we create new rules to support it?

**Comment by danieldietsch** [comment]
There is the ``BndResponsePatternTT``:
``If EXPR holds for at least DURATION, then EXPR holds afterwards for at least DURATION``
https://ultimate-pa.github.io/hanfor/references/patterns.html#bndresponsepatterntt

But you are right; there is currently no pattern that supports this requirement. Do you need it? 
If so, do you really want to say "holds for 1s", i.e., for exactly 1s? This is generally not advisable because in real systems, it is impossible to achieve exact timings. We could add a pattern that triggers with ``less than`` and leads to ``at least``.

**Comment by IridescentL** [comment]
Yeah, 'exactly 1s' is not proper for a real system and we don't need this kind of exact timing.

**Comment by danieldietsch** [comment]
So, it would help you if we would add a pattern ``If EXPR holds for at most DURATION, then EXPR holds afterwards for at least DURATION``?

**Comment by IridescentL** [comment]
It's very considerate for you to have that intention. But we don't need it right now, so we won't bother you to do it at this moment. You're very nice. Thanks for your help!
